version: '3.4'

services:
  ku_oj_db:
    image: mysql:latest
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "--silent"
        ]
      interval: 10s
      timeout: 100s
      retries: 1000
    environment:
      - MYSQL_ROOT_PASSWORD=Random1.
      - MYSQL_DATABASE=ku_oj
      - MYSQL_PASSWORD=Random1.
    ports:
      - "3300:3306"
    volumes:
      - ./migrations/ku_oj.sql:/docker-entrypoint-initdb.d/ku_oj.sql
  ku_oj_redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 50s
      timeout: 100s
      retries: 1000
      start_period: 30s
    ports:
      - "5000:6379"
    volumes:
      - cache:/data
  ku_oj_api:
    image: shahriarkabir/ku_oj_api:latest
    ports:
      - "8080:8080"
    environment:
      - jwtSecret=erhgrehgirehgregir
      - dbPort=3306
      - dbName=ku_oj
      - dbUser=root
      - dbPassword=Random1.
      - dbHost=ku_oj_db
      - ssl=null
      - redisHost=ku_oj_redis
      - redisPort=6379
    depends_on:
      ku_oj_db:
        condition: service_healthy
      ku_oj_redis:
        condition: service_healthy

  ku_oj_ws:
    image: shahriarkabir/ku_oj_ws:latest
    ports:
      - "8081:8081"
  ku_oj:
    image: shahriarkabir/ku_oj:latest
    environment:
      NODE_ENV: production
      REACT_APP_SERVER_URL: http://192.168.138.134:8080
      REACT_APP_WS_URL: wss://192.168.138.134:8081/
    ports:
      - 3000:3000
    depends_on:
      - ku_oj_db
      - ku_oj_api
      - ku_oj_ws
volumes:
  mysql-data:
  cache:
    driver: local
