events {}

http {

    upstream ku_api {
        least_conn;

        server ku_oj_api:8080;
        server ku_oj_api:8080;
        server ku_oj_api:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://ku_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}